---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: staging
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.nginx: glob:1.9.*
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.15
        ports:
        - containerPort: 80
